var lykb_content = '<table class="tg"style="margin:0 auto;">\
<tr><td class="tg-lyaj"rowspan="4">第一天<br/>请大家着<br/>新汉服</td><td class="tg-031e"><strong>开启礼仪师成长之旅</strong></td><td class="tg-z2zr">礼仪师的深度：历史是因、未来是果<br/>礼仪师的宽度：礼仪不是教条、不必上纲上线<br/>礼仪师的风度：礼人不答，反其敬</td><td class="tg-s6z2"rowspan="4">程从正</td></tr><tr><td class="tg-031e"><strong>从尊重开始解读</strong></td><td class="tg-z2zr">己所不欲、勿施于人<br/>己所甚欲、勿施于人<br/>入乡随俗、因地制宜<br/>谦让才有礼、礼让不过三<br/>有型才有礼、悦己又悦人</td></tr><tr><td class="tg-031e"><strong>从礼规展开探究</strong></td><td class="tg-z2zr">卑己尊人的传统称谓<br/>中西合璧的现代称谓<br/>文化传承的“名”和“字”<br/>中式传统仪态的特点<br/>经立、徐行、尸坐的演示<br/>拱手与握手：谁更高一手？<br/>颔首与点头：君子和绅士都是礼仪达人<br/>跪拜礼与觐见礼：威权时代的文明索引<br/>万福礼与屈膝礼：您万福or陛下金安</td></tr><tr><td class="tg-031e"><strong>礼仪师的责任</strong></td><td class="tg-z2zr">传统礼仪现代化<br/>国际礼仪中国化<br/>中国礼仪国际化</td></tr>\
<tr><td class="tg-lyaj">第一晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、营养是最好的美容；<br/>2、健康是美丽的源泉。</td><td class="tg-s6z2">刘伟</td></tr>\
<tr><td class="tg-lyaj"rowspan="4">第二天<br/>请大家着<br/>职场正装</td><td class="tg-031e"><strong>眼神</strong>——<br/>一身之戏在于脸<br/>一脸之戏在于眼</td><td class="tg-z2zr">心明眼亮——清澈坦然的眼神训练<br/>慈眉善目——温和柔美的眼神训练<br/>另眼相看——热情大方的眼神训练</td><td class="tg-s6z2"rowspan="4">徐文波</td></tr><tr><td class="tg-031e"><strong>微笑</strong>——<br/>谁偷走了你的微笑<br/>微笑是最好的名片</td><td class="tg-z2zr">眉开眼笑训练法<br/>口笑、心笑训练法<br/>眼笑、口笑、心笑综合练习</td></tr><tr><td class="tg-031e"><strong>站姿与坐姿</strong>——<br/>力学和美学<br/>和谐才优雅</td><td class="tg-z2zr">哪些站姿和坐姿最易让身体变形？<br/>问题站姿的矫正方法<br/>问题坐姿的矫正方法</td></tr><tr><td class="tg-031e"><strong>走姿与蹲姿</strong>——<br/>走得像不如走得好<br/>走得好不如走得美</td><td class="tg-z2zr">礼仪走姿与舞台走姿的区别<br/>行走、侧身、转身、留头的综合训练<br/>不同场合的优雅蹲姿</td></tr>\
<tr><td class="tg-lyaj">第二天晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、汽车4S店的课程设计；<br>2、汽车行业培训的课程开发。</td><td class="tg-s6z2">张颖亭</td></tr>\
<tr><td class="tg-lyaj"rowspan="3">第三天<br>请大家着<br>职场正装</td><td class="tg-031e"><strong>礼仪师优雅仪态</strong><br/>综合训练1</td><td class="tg-z2zr">注视礼——心、眼结合训练<br/>问候礼——口、眼结合训练<br/>指引礼——手、眼结合训练</td><td class="tg-s6z2"rowspan="3">徐文波</td></tr><tr><td class="tg-031e"><strong>礼仪师优雅仪态</strong><br/>综合训练2</td><td class="tg-z2zr">鞠躬礼——有形有心才能表情达意<br/>握手礼——有情有度才能优雅得体<br/>名片礼——有章有序才能有礼有节</td></tr><tr><td class="tg-031e"><strong>服务礼仪综合运用</strong></td><td class="tg-z2zr">金融行业服务规范<br/>金融行业服务礼仪角色扮演<br/>医护行业服务规范<br/>医护行业服务礼仪角色扮演<br/>餐饮行业服务规范<br/>餐饮行业服务礼仪角色扮演</td></tr>\
<tr><td class="tg-lyaj">第三天晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、如何将短期礼仪培训做成长期有效的培训；<br/>2、如何制作长期礼仪培训方案；如何将短期礼仪培训做成长期有效的培训；<br/>3、企业现场督导培训五个模块。</td><td class="tg-s6z2">郭丽</td></tr>\
<tr><td class="tg-lyaj"rowspan="2">第四天<br/>请大家着<br/>时尚职场装</td><td class="tg-031e"><strong>衣服穿不对</strong><br/><strong>事业受拖累</strong></td><td class="tg-z2zr">职场着装的新趋势<br/>男土职业装“正"在哪里一一事业是男人的形象<br/>\
                女士职业装“正"在哪里一一形象是女人的事业<br/>男土配饰的型、色、质<br/>女士配饰的型、色、质<br/>形象礼仪师的穿衣经<br/></td><td class="tg-s6z2"rowspan="2">程从正</td></tr><tr><td class="tg-031e"><strong>位次安排不对</strong><br/><strong>其它努力都白费</strong></td><td class="tg-z2zr">中式位次礼仪的核心是什么？<br/>国际通行位次礼仪的标准是什么？<br/>中餐座次——两招理清万千头绪<br/>会谈座次——不同的左主右客<br/>合影位次——千差万别中的潜在规律<br/>乘车座次——国际通行规则</td></tr>\
				<tr><td class="tg-lyaj">第四天晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、PPT的排版设计；<br/>2、PPT的制作技巧。</td><td class="tg-s6z2">焦盈鑫</td></tr>\
				<tr><td class="tg-lyaj"rowspan="2">第五天<br/>请大家着<br/>时尚职场装</td><td class="tg-031e"><strong>声音美学</strong></td><td class="tg-z2zr">1、声音的美学原理；<br/>2、如何让声音铿锵有力；<br/>3、找到适合自己的声音形象；<br/>4、美化自己声音的几种方法；<br/>5、如何塑造自己的声音影响力；</td><td class="tg-s6z2"rowspan="2">逯瑶</td></tr><tr><td class="tg-031e"><strong>表达礼仪</strong></td><td class="tg-z2zr">1、激活大脑的语言天赋；<br/>2、开场和结尾的激情燃放；<br/>3、教学现场的氛围营造；<br/>4、讲师情绪的科学调节；<br/>5、无声胜有声的课程营销；<br/>6、解决课堂突发事件的有效办法。</td></tr>\
				<!--<tr><td class="tg-lyaj">第五天晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、用心灵唤醒能量<br/>2、用舞蹈展现自我。</td><td class="tg-s6z2">李晓</td></tr>\
				<tr><td class="tg-lyaj">第五天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">本班风尚晚会</strong>（全班同学都参加）<br>1、请着礼服入场；<br>2、请准备表演节目。</td><td class="tg-s6z2">班委会</td></tr>--><tr><td class="tg-lyaj">第五晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong>（实景呈现：人民大会堂会务礼仪）<br>1、会议服务准备工作；<br>2、会议服务规范；<br>3、会议服务注意事项。</td><td class="tg-s6z2">李媛</td></tr>\
				<tr><td class="tg-lyaj"rowspan="2">第六天<br/>着装没有要求</td><td class="tg-031e"><strong>礼仪师成长第一阶<br/>知己知彼</strong></td><td class="tg-z2zr">自我审视：我的优点在哪里、不足在哪里<br/>自我完善：制定自己的成长计划<br/>学员结构与学习心理的分析方法<br/>教学计划与学习目标的准确对接<br/>教学场地的几种布局模式</td><td class="tg-s6z2"rowspan="2">于焕新</td></tr><tr><td class="tg-031e"><strong>礼仪师成长第二阶<br/>方法为王</strong></td><td class="tg-z2zr">开场的N种方法——哪种开场更适合你<br/>破冰与分组——让大家都是主角<br/>讲授、示范和案例分析——简洁、准确是王道<br/>情景模拟、角色扮演和沙盘——是编剧也是导演<br/>课程总结——回顾是再次自我审视</td></tr>\
				<tr><td class="tg-lyaj">第六天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">本班鸡尾酒会</strong>（全班同学都参加）<br>1、请着礼服入场；<br>2、西餐礼仪实战演练；<br>3、鸡尾酒会。</td><td class="tg-s6z2">佟静</td></tr>\
				<tr><td class="tg-lyaj"rowspan="2">第七天<br/>着装没有要求</td><td class="tg-031e"><strong>礼仪师成长第三阶<br>自信与突破</strong></td><td class="tg-z2zr">真诚——最有力量的表达<br>自信——充分准备才能胸有成竹<br>突破——我的敌人是我自己<br>培训师自身情绪的管理途径<br>学员的情绪管理与调节技巧<br>威信建立——功到自然成</td><td class="tg-s6z2"rowspan="2">于焕新</td></tr><tr><td class="tg-031e"><strong>礼仪师成长第四阶<br>翻开新篇章</strong></td><td class="tg-z2zr">培训调研——从大局着眼，从细节展开<br>课程开发——艺术家换位企业家在思考<br>培训PPT——是技术也是艺术<br>风格养成——你的思想是一面旗帜</td></tr>\
				<tr><td class="tg-lyaj">第七天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>课程演绎与演讲技巧<br>1、凤头－开头精彩，引人注目；<br>2、猪肚－内容充实，引人入胜；<br>3、豹尾－结尾有劲，引人回味。</td><td class="tg-s6z2">马瑛</td></tr>\
				<tr><td class="tg-lyaj"rowspan="3">第八天<br/>请大家着<br/>职业正装</td><td class="tg-031e"rowspan="3">模拟教学演讲考试</td><td class="tg-z2zr"><strong class="mianfei">本班毕业的优秀培训师可签约中国形象礼仪行业风尚圈讲师团</strong></td><td class="tg-s6z2"rowspan="3">中国形象礼仪行业<br>风尚圈评委团</td></tr><tr><td class="tg-z2zr"><strong class="mianfei">风尚圈根据您的教学特点为您就近推荐企业培训</strong></td></tr><tr><td class="tg-z2zr"><strong class="mianfei">您的个人简介都可登载在形象礼仪行业风尚圈官方网站</strong></td></tr></table>'

var xxkb_content='<table class="tg"style="margin:0 auto;">\
<tr><td class="tg-lyaj"rowspan="6">第一天<br><strong>穿对色彩<br/>就精彩</strong></td><td class="tg-031e">开班式</td><td class="tg-z2zr">暖色人的特点与色彩搭配</td><td class="tg-s6z2"rowspan="6">路平</td></tr><tr><td class="tg-031e">色彩表情与色彩心理</td><td class="tg-z2zr">艳色人的特点与色彩搭配</td></tr><tr><td class="tg-031e">人体色彩的分类</td><td class="tg-z2zr">浊色人的特点与色彩搭配</td></tr><tr><td class="tg-031e">深色人的特点与色彩搭配</td><td class="tg-z2zr">实用的色彩搭配规律</td></tr><tr><td class="tg-031e">浅色人的特点与色彩搭配</td><td class="tg-z2zr">常见的色彩搭配误区</td></tr><tr><td class="tg-031e">冷色人的特点与色彩搭配</td><td class="tg-z2zr">个人色彩综合分析流程练习</td></tr>\
<tr><td class="tg-lyaj">第一天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong>（希望了解各种性格养成的同学选修）<br>1、九型人格——了解各类性格的特点和成因；<br>2、九型人格对生活工作的帮助。</td><td class="tg-s6z2">王梓沣</td></tr>\
<tr><td class="tg-lyaj"rowspan="6">第二天<br><strong>选对款型<br/>就美丽</strong></td><td class="tg-031e">脸型与领型的关系</td><td class="tg-z2zr">女士直线体型与服装款式选择</td><td class="tg-s6z2"rowspan="6">路平</td></tr><tr><td class="tg-031e">脸型与服装廓形的关系</td><td class="tg-z2zr">柔和直线体型与服装款式选择</td></tr><tr><td class="tg-031e">五官与眼镜等饰品的选择</td><td class="tg-z2zr">直线柔和体型与服装款式选择</td></tr><tr><td class="tg-031e">五官与服装图案的关系</td><td class="tg-z2zr">女士曲线体型与服装款式选择</td></tr><tr><td class="tg-031e">服装款式的基础知识</td><td class="tg-z2zr">男士直线体型与服装选择</td></tr><tr><td class="tg-031e">服装廓形与细节分析</td><td class="tg-z2zr">男士柔和体型与服装选择</td></tr>\
<tr><td class="tg-lyaj">第二天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、科学发声的艺术修炼；<br/>2、胸腔、鼻腔、口腔的发声技巧；<br/>3、吐字清晰、音色纯正有窍门；<br/>4、行之有效的练习方法。</td><td class="tg-s6z2">陈子涵</td></tr>\
<tr><td class="tg-lyaj"rowspan="6">第三天<br/><strong>整体形象中的<br/>发型与妆面</strong></td><td class="tg-031e">化妆造型：三分长相七分打扮</td><td class="tg-z2zr">晚宴化妆的特点</td><td class="tg-s6z2"rowspan="6">路平</td></tr><tr><td class="tg-031e">发型与整体风格的协调</td><td class="tg-z2zr">约会化妆的特点</td></tr><tr><td class="tg-031e">各种发型的特点分析</td><td class="tg-z2zr">快速职场化妆的方法</td></tr><tr><td class="tg-031e">发型设计的常用方法</td><td class="tg-z2zr">休闲化妆的个性表现</td></tr><tr><td class="tg-031e">发型与场合的关系</td><td class="tg-z2zr">示范和练习（请携带化妆工具）</td></tr><tr><td class="tg-031e">发型与服装的关系</td><td class="tg-z2zr">发型与脸型、体型的和谐搭配</td></tr>\
<tr><td class="tg-lyaj">第三天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、基本站姿、基础站姿、走姿、转体、脚位的训练；<br>2、汉服仪态的特点；<br>3、汉服秀的T台训练。</td><td class="tg-s6z2">赵佳男</td></tr>\
<tr><td class="tg-lyaj"rowspan="3">第四天<br><strong>六类人群的<br/>服装搭配演练</strong></td><td class="tg-031e">都市休闲的个性化风格塑造</td><td class="tg-z2zr">企业白领的职业形象塑造</td><td class="tg-s6z2"rowspan="3">文琦</td></tr><tr><td class="tg-031e">职业老师的端庄风格塑造</td><td class="tg-z2zr">公务人员的亲民形象塑造</td></tr><tr><td class="tg-031e">形象礼仪师的专业形象塑造</td><td class="tg-z2zr">严肃职场的权威形象塑造</td></tr>\
<tr><td class="tg-lyaj">第四天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、新汉服T台秀；<br>2、“中华女子成人礼--笄礼”实景展示。</td><td class="tg-s6z2">全体同学</td></tr>\
<tr><td class="tg-lyaj"rowspan="4">第五天<br><strong>八种社交的<br/>服装搭配演练</strong></td><td class="tg-031e">日间社交场合——从保守到优雅</td><td class="tg-z2zr">晚间社交场合——从个性到华丽</td><td class="tg-s6z2"rowspan="4">文琦</td></tr><tr><td class="tg-031e">下午茶着装——休闲优雅</td><td class="tg-z2zr">同学会着装——大方轻松</td></tr><tr><td class="tg-031e">庆典着装——端庄优雅</td><td class="tg-z2zr">鸡尾酒会着装——性感个性</td></tr><tr><td class="tg-031e">追悼会着装——肃穆</td><td class="tg-z2zr">正式晚宴——隆重华丽</td></tr>\
<tr><td class="tg-lyaj">第五天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、形象管理新业态——线上教学的方法；<br/>2、形象管理师的百变丝巾。</td><td class="tg-s6z2">翟夏妍</td></tr>\
<tr><td class="tg-lyaj"rowspan="5">第六天<br><strong>气质就在<br/>穿对风格<strong/></td><td class="tg-031e">行为主义美学的基本原理</td><td class="tg-z2zr">形、色、质的转换方法</td><td class="tg-s6z2"rowspan="5">韩久九</td></tr><tr><td class="tg-031e">个人形象风格的表现形式</td><td class="tg-z2zr">风格管理视窗的基本原理</td></tr><tr><td class="tg-031e">量感大、小与服装廓形</td><td class="tg-z2zr">国际形象设计体系综合应用</td></tr><tr><td class="tg-031e">体型直、曲与服装线条</td><td class="tg-z2zr">个人形象定位的基本技巧</td></tr><tr><td class="tg-031e">风格动、静与服装色彩</td><td class="tg-z2zr">现代形象管理的发展趋势</td></tr>\
<tr><td class="tg-lyaj">第六天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、形象管理师的心灵成长；<br>2、阳光心态与职业素养。</td><td class="tg-s6z2">于焕新</td></tr>\
<tr><td class="tg-lyaj"rowspan="4">第七天<br/><strong>管好自己才能<br/>帮到客户</strong></td><td class="tg-031e">形象管理中的隐性因素</td><td class="tg-z2zr">个人生活方式分析</td><td class="tg-s6z2"rowspan="4">韩久九</td></tr><tr><td class="tg-031e">流行元素的合理运用</td><td class="tg-z2zr">场合着装风格的转换</td></tr><tr><td class="tg-031e">个人形象心理分析方法</td><td class="tg-z2zr">有效的扬长避短技巧</td></tr><tr><td class="tg-031e">个人嗜好与着装关系</td><td class="tg-z2zr">衣橱管理的科学方法</td></tr>\
<tr><td class="tg-lyaj">第七天晚上<br/>16:30-17:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">注册形象管理师考试</strong></td><td class="tg-s6z2">评委团</td></tr></table>'


var xxlykb_content='<table class="tg"style="margin:0 auto;">\
<tr><td class="tg-lyaj"rowspan="6">第一天<br><strong>穿对色彩<br/>就精彩</strong></td><td class="tg-031e">开班式</td><td class="tg-z2zr">暖色人的特点与色彩搭配</td><td class="tg-s6z2"rowspan="6">路平</td></tr><tr><td class="tg-031e">色彩表情与色彩心理</td><td class="tg-z2zr">艳色人的特点与色彩搭配</td></tr><tr><td class="tg-031e">人体色彩的分类</td><td class="tg-z2zr">浊色人的特点与色彩搭配</td></tr><tr><td class="tg-031e">深色人的特点与色彩搭配</td><td class="tg-z2zr">实用的色彩搭配规律</td></tr><tr><td class="tg-031e">浅色人的特点与色彩搭配</td><td class="tg-z2zr">常见的色彩搭配误区</td></tr><tr><td class="tg-031e">冷色人的特点与色彩搭配</td><td class="tg-z2zr">个人色彩综合分析流程练习</td></tr>\
<tr><td class="tg-lyaj">第一天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong>（希望了解各种性格养成的同学选修）<br>1、九型人格——了解各类性格的特点和成因；<br>2、九型人格对生活工作的帮助。</td><td class="tg-s6z2">王梓沣</td></tr>\
<tr><td class="tg-lyaj"rowspan="6">第二天<br><strong>选对款型<br/>就美丽</strong></td><td class="tg-031e">脸型与领型的关系</td><td class="tg-z2zr">女士直线体型与服装款式选择</td><td class="tg-s6z2"rowspan="6">路平</td></tr><tr><td class="tg-031e">脸型与服装廓形的关系</td><td class="tg-z2zr">柔和直线体型与服装款式选择</td></tr><tr><td class="tg-031e">五官与眼镜等饰品的选择</td><td class="tg-z2zr">直线柔和体型与服装款式选择</td></tr><tr><td class="tg-031e">五官与服装图案的关系</td><td class="tg-z2zr">女士曲线体型与服装款式选择</td></tr><tr><td class="tg-031e">服装款式的基础知识</td><td class="tg-z2zr">男士直线体型与服装选择</td></tr><tr><td class="tg-031e">服装廓形与细节分析</td><td class="tg-z2zr">男士柔和体型与服装选择</td></tr>\
<tr><td class="tg-lyaj">第二天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、科学发声的艺术修炼；<br/>2、胸腔、鼻腔、口腔的发声技巧；<br/>3、吐字清晰、音色纯正有窍门；<br/>4、行之有效的练习方法。</td><td class="tg-s6z2">陈子涵</td></tr>\
<tr><td class="tg-lyaj"rowspan="6">第三天<br/><strong>整体形象中的<br/>发型与妆面</strong></td><td class="tg-031e">化妆造型：三分长相七分打扮</td><td class="tg-z2zr">晚宴化妆的特点</td><td class="tg-s6z2"rowspan="6">路平</td></tr><tr><td class="tg-031e">发型与整体风格的协调</td><td class="tg-z2zr">约会化妆的特点</td></tr><tr><td class="tg-031e">各种发型的特点分析</td><td class="tg-z2zr">快速职场化妆的方法</td></tr><tr><td class="tg-031e">发型设计的常用方法</td><td class="tg-z2zr">休闲化妆的个性表现</td></tr><tr><td class="tg-031e">发型与场合的关系</td><td class="tg-z2zr">示范和练习（请携带化妆工具）</td></tr><tr><td class="tg-031e">发型与服装的关系</td><td class="tg-z2zr">发型与脸型、体型的和谐搭配</td></tr>\
<tr><td class="tg-lyaj">第三天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、基本站姿、基础站姿、走姿、转体、脚位的训练；<br>2、汉服仪态的特点；<br>3、汉服秀的T台训练。</td><td class="tg-s6z2">赵佳男</td></tr>\
<tr><td class="tg-lyaj"rowspan="3">第四天<br><strong>六类人群的<br/>服装搭配演练</strong></td><td class="tg-031e">都市休闲的个性化风格塑造</td><td class="tg-z2zr">企业白领的职业形象塑造</td><td class="tg-s6z2"rowspan="3">文琦</td></tr><tr><td class="tg-031e">职业老师的端庄风格塑造</td><td class="tg-z2zr">公务人员的亲民形象塑造</td></tr><tr><td class="tg-031e">形象礼仪师的专业形象塑造</td><td class="tg-z2zr">严肃职场的权威形象塑造</td></tr>\
<tr><td class="tg-lyaj">第四天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、新汉服T台秀；<br>2、“中华女子成人礼--笄礼”实景展示。</td><td class="tg-s6z2">全体同学</td></tr>\
<tr><td class="tg-lyaj"rowspan="4">第五天<br><strong>八种社交的<br/>服装搭配演练</strong></td><td class="tg-031e">日间社交场合——从保守到优雅</td><td class="tg-z2zr">晚间社交场合——从个性到华丽</td><td class="tg-s6z2"rowspan="4">文琦</td></tr><tr><td class="tg-031e">下午茶着装——休闲优雅</td><td class="tg-z2zr">同学会着装——大方轻松</td></tr><tr><td class="tg-031e">庆典着装——端庄优雅</td><td class="tg-z2zr">鸡尾酒会着装——性感个性</td></tr><tr><td class="tg-031e">追悼会着装——肃穆</td><td class="tg-z2zr">正式晚宴——隆重华丽</td></tr>\
<tr><td class="tg-lyaj">第五天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、形象管理新业态——线上教学的方法；<br/>2、形象管理师的百变丝巾。</td><td class="tg-s6z2">翟夏妍</td></tr>\
<tr><td class="tg-lyaj"rowspan="5">第六天<br><strong>气质就在<br/>穿对风格<strong/></td><td class="tg-031e">行为主义美学的基本原理</td><td class="tg-z2zr">形、色、质的转换方法</td><td class="tg-s6z2"rowspan="5">韩久九</td></tr><tr><td class="tg-031e">个人形象风格的表现形式</td><td class="tg-z2zr">风格管理视窗的基本原理</td></tr><tr><td class="tg-031e">量感大、小与服装廓形</td><td class="tg-z2zr">国际形象设计体系综合应用</td></tr><tr><td class="tg-031e">体型直、曲与服装线条</td><td class="tg-z2zr">个人形象定位的基本技巧</td></tr><tr><td class="tg-031e">风格动、静与服装色彩</td><td class="tg-z2zr">现代形象管理的发展趋势</td></tr>\
<tr><td class="tg-lyaj">第六天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、形象管理师的心灵成长；<br>2、阳光心态与职业素养。</td><td class="tg-s6z2">于焕新</td></tr>\
<tr><td class="tg-lyaj"rowspan="4">第七天<br/><strong>管好自己才能<br/>帮到客户</strong></td><td class="tg-031e">形象管理中的隐性因素</td><td class="tg-z2zr">个人生活方式分析</td><td class="tg-s6z2"rowspan="4">韩久九</td></tr><tr><td class="tg-031e">流行元素的合理运用</td><td class="tg-z2zr">场合着装风格的转换</td></tr><tr><td class="tg-031e">个人形象心理分析方法</td><td class="tg-z2zr">有效的扬长避短技巧</td></tr><tr><td class="tg-031e">个人嗜好与着装关系</td><td class="tg-z2zr">衣橱管理的科学方法</td></tr>\
<tr><td class="tg-lyaj"rowspan="4">第八天<br/>请大家着<br/>新汉服</td><td class="tg-031e"><strong>开启礼仪师成长之旅</strong></td><td class="tg-z2zr">礼仪师的深度：历史是因、未来是果<br/>礼仪师的宽度：礼仪不是教条、不必上纲上线<br/>礼仪师的风度：礼人不答，反其敬</td><td class="tg-s6z2"rowspan="4">程从正</td></tr><tr><td class="tg-031e"><strong>从尊重开始解读</strong></td><td class="tg-z2zr">己所不欲、勿施于人<br/>己所甚欲、勿施于人<br/>入乡随俗、因地制宜<br/>谦让才有礼、礼让不过三<br/>有型才有礼、悦己又悦人</td></tr><tr><td class="tg-031e"><strong>从礼规展开探究</strong></td><td class="tg-z2zr">卑己尊人的传统称谓<br/>中西合璧的现代称谓<br/>文化传承的“名”和“字”<br/>中式传统仪态的特点<br/>经立、徐行、尸坐的演示<br/>拱手与握手：谁更高一手？<br/>颔首与点头：君子和绅士都是礼仪达人<br/>跪拜礼与觐见礼：威权时代的文明索引<br/>万福礼与屈膝礼：您万福or陛下金安</td></tr><tr><td class="tg-031e"><strong>礼仪师的责任</strong></td><td class="tg-z2zr">传统礼仪现代化<br/>国际礼仪中国化<br/>中国礼仪国际化</td></tr>\
<tr><td class="tg-lyaj">第八晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、营养是最好的美容；<br/>2、健康是美丽的源泉。</td><td class="tg-s6z2">刘伟</td></tr>\
<tr><td class="tg-lyaj"rowspan="4">第九天<br/>请大家着<br/>职场正装</td><td class="tg-031e"><strong>眼神</strong>——<br/>一身之戏在于脸<br/>一脸之戏在于眼</td><td class="tg-z2zr">心明眼亮——清澈坦然的眼神训练<br/>慈眉善目——温和柔美的眼神训练<br/>另眼相看——热情大方的眼神训练</td><td class="tg-s6z2"rowspan="4">徐文波</td></tr><tr><td class="tg-031e"><strong>微笑</strong>——<br/>谁偷走了你的微笑<br/>微笑是最好的名片</td><td class="tg-z2zr">眉开眼笑训练法<br/>口笑、心笑训练法<br/>眼笑、口笑、心笑综合练习</td></tr><tr><td class="tg-031e"><strong>站姿与坐姿</strong>——<br/>力学和美学<br/>和谐才优雅</td><td class="tg-z2zr">哪些站姿和坐姿最易让身体变形？<br/>问题站姿的矫正方法<br/>问题坐姿的矫正方法</td></tr><tr><td class="tg-031e"><strong>走姿与蹲姿</strong>——<br/>走得像不如走得好<br/>走得好不如走得美</td><td class="tg-z2zr">礼仪走姿与舞台走姿的区别<br/>行走、侧身、转身、留头的综合训练<br/>不同场合的优雅蹲姿</td></tr>\
<tr><td class="tg-lyaj">第九天晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>1、汽车4S店的课程设计；<br>2、汽车行业培训的课程开发。</td><td class="tg-s6z2">张颖亭</td></tr>\
<tr><td class="tg-lyaj"rowspan="3">第十天<br>请大家着<br>职场正装</td><td class="tg-031e"><strong>礼仪师优雅仪态</strong><br/>综合训练1</td><td class="tg-z2zr">注视礼——心、眼结合训练<br/>问候礼——口、眼结合训练<br/>指引礼——手、眼结合训练</td><td class="tg-s6z2"rowspan="3">徐文波</td></tr><tr><td class="tg-031e"><strong>礼仪师优雅仪态</strong><br/>综合训练2</td><td class="tg-z2zr">鞠躬礼——有形有心才能表情达意<br/>握手礼——有情有度才能优雅得体<br/>名片礼——有章有序才能有礼有节</td></tr><tr><td class="tg-031e"><strong>服务礼仪综合运用</strong></td><td class="tg-z2zr">金融行业服务规范<br/>金融行业服务礼仪角色扮演<br/>医护行业服务规范<br/>医护行业服务礼仪角色扮演<br/>餐饮行业服务规范<br/>餐饮行业服务礼仪角色扮演</td></tr>\
<tr><td class="tg-lyaj">第十天晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、如何将短期礼仪培训做成长期有效的培训；<br/>2、如何制作长期礼仪培训方案；<br/>3、企业现场督导培训五个模块。</td><td class="tg-s6z2">郭丽</td></tr>\
<tr><td class="tg-lyaj"rowspan="2">第十一天<br/>请大家着<br/>时尚职场装</td><td class="tg-031e"><strong>衣服穿不对</strong><br/><strong>事业受拖累</strong></td><td class="tg-z2zr">职场着装的新趋势<br/>男土职业装“正”在哪里一一事业是男人的形象<br/>女士职业装“正”在哪里一一形象是女人的事业<br/>男土配饰的型、色、质<br/>女士配饰的型、色、质<br/>形象礼仪师的穿衣经<br/></td><td class="tg-s6z2" rowspan="2">程从正</td></tr><tr><td class="tg-031e"><strong>位次安排不对</strong><br/><strong>其它努力都白费</strong></td><td class="tg-z2zr">中式位次礼仪的核心是什么？<br/>国际通行位次礼仪的标准是什么？<br/>中餐座次——两招理清万千头绪<br/>会谈座次——不同的左主右客<br/>合影位次——千差万别中的潜在规律<br/>乘车座次——国际通行规则</td></tr>\
<tr><td class="tg-lyaj">第十一天晚上<br>16:30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br/>1、PPT的排版设计；<br/>2、PPT的制作技巧。</td><td class="tg-s6z2">焦盈鑫</td></tr>\
<tr><td class="tg-lyaj"rowspan="2">第十二天<br/>请大家着<br/>时尚职场装</td><td class="tg-031e"><strong>声音美学</strong></td><td class="tg-z2zr">1、声音的美学原理；<br/>2、如何让声音铿锵有力；<br/>3、找到适合自己的声音形象；<br/>4、美化自己声音的几种方法；<br/>5、如何塑造自己的声音影响力；</td><td class="tg-s6z2"rowspan="2">逯瑶</td></tr><tr><td class="tg-031e"><strong>表达礼仪</strong></td><td class="tg-z2zr">1、激活大脑的语言天赋；<br/>2、开场和结尾的激情燃放；<br/>3、教学现场的氛围营造；<br/>4、讲师情绪的科学调节；<br/>5、无声胜有声的课程营销；<br/>6、解决课堂突发事件的有效办法。</td></tr>\
<tr><td class="tg-lyaj">第十二天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong>（实景呈现：人民大会堂会务礼仪）<br>1、会议服务准备工作；<br>2、会议服务规范；<br>3、会议服务注意事项。</td><td class="tg-s6z2">李媛</td></tr>\
<tr><td class="tg-lyaj"rowspan="2">第十三天<br/>着装没有要求</td><td class="tg-031e"><strong>礼仪师成长第一阶<br/>知己知彼</strong></td><td class="tg-z2zr">自我审视：我的优点在哪里、不足在哪里<br/>自我完善：制定自己的成长计划<br/>学员结构与学习心理的分析方法<br/>教学计划与学习目标的准确对接<br/>教学场地的几种布局模式</td><td class="tg-s6z2"rowspan="2">于焕新</td></tr><tr><td class="tg-031e"><strong>礼仪师成长第二阶<br/>方法为王</strong></td><td class="tg-z2zr">开场的N种方法——哪种开场更适合你<br/>破冰与分组——让大家都是主角<br/>讲授、示范和案例分析——简洁、准确是王道<br/>情景模拟、角色扮演和沙盘——是编剧也是导演<br/>课程总结——回顾是再次自我审视</td></tr>\
<tr><td class="tg-lyaj">第十三天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">本班鸡尾酒会</strong>（全班同学都参加）<br>1、请着礼服入场；<br>2、西餐礼仪实战演练；<br>3、鸡尾酒会。</td><td class="tg-s6z2">佟静</td></tr>\
<tr><td class="tg-lyaj"rowspan="2">第十四天<br/>着装没有要求</td><td class="tg-031e"><strong>礼仪师成长第三阶<br>自信与突破</strong></td><td class="tg-z2zr">真诚——最有力量的表达<br>自信——充分准备才能胸有成竹<br>突破——我的敌人是我自己<br>培训师自身情绪的管理途径<br>学员的情绪管理与调节技巧<br>威信建立——功到自然成</td><td class="tg-s6z2"rowspan="2">于焕新</td></tr><tr><td class="tg-031e"><strong>礼仪师成长第四阶<br>翻开新篇章</strong></td><td class="tg-z2zr">培训调研——从大局着眼，从细节展开<br>课程开发——艺术家换位企业家在思考<br>培训PPT——是技术也是艺术<br>风格养成——你的思想是一面旗帜</td></tr>\
<tr><td class="tg-lyaj">第十四天晚上<br>16：30-18:30</td><td class="tg-031e"colspan="2"><strong class="mianfei">免费选修课</strong><br>课程演绎与演讲技巧<br>1、凤头－开头精彩，引人注目；<br>2、猪肚－内容充实，引人入胜；<br>3、豹尾－结尾有劲，引人回味。</td><td class="tg-s6z2">马瑛</td></tr>\
<tr><td class="tg-lyaj"rowspan="3">第十五天<br/>请大家着<br/>职业正装</td><td class="tg-031e"rowspan="3">模拟教学演讲考试</td><td class="tg-z2zr"><strong class="mianfei">本班毕业的优秀培训师可签约中国形象礼仪行业风尚圈讲师团</strong></td><td class="tg-s6z2"rowspan="3">中国形象礼仪行业风尚圈评委团</td></tr><tr><td class="tg-z2zr"><strong class="mianfei">风尚圈根据您的教学特点为您就近推荐企业培训</strong></td></tr><tr><td class="tg-z2zr"><strong class="mianfei">您的个人简介都可登载在形象礼仪行业风尚圈官方网站</strong></td></tr></table>'

var lykb = document.getElementById("lykb")
if(lykb){
	lykb.innerHTML = lykb_content
}
 

 var xxkb = document.getElementById("xxkb")
 if(xxkb){
	 xxkb.innerHTML = xxkb_content
 }


var xxlykb = document.getElementById("xxlykb")
if(xxlykb){
	xxlykb.innerHTML = xxlykb_content
}
